sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: HrGcdkY2VKV87M4E3hqOVpT+E9ef9GsHF0z6zOcYAzvxt6LPG8Kt3WkyXkz9R/NGCAfAhEn0ERcl2DuxDdHHCYzUJWc+pN/UDyLJ6Hf4PAS0IAw1Z1bPaU10QdtXYH4g4YzpGwIXpE/jFbaiw6CgGmzMX+i3m898HF5QYOlLadKzymKbMje9lAaEQ46rmmAoVrQPtUsvKFOTzPyXeigi7mal9Hrr36vU1HgUKtyjrzIwiJBcGcxxbTdSg+Xyh9/oWCVcJIbcy1p6lbBo/ldroXJvVf53z7CRYIl/exfNbxZ1t5v3/HxzZ5Z/ZiTE07Yri8CrmoqvQ/eo9pa5+ov+vJoC/C6wsdDZhGeMhhF3gtSIq+znwMaAJ6q+9LPPD6ml0Dm0q2YkbXyVFqDB0/cEbBW1dnadTNUyX2D3jxcS9uJYaqTDEmKck1Wgdpv7xNNg5TZah6CueXI4Wh6ypgHH+9dkmEKFl+N91+6pO+LC+0ALgJw4Kq3t1eMeNyARlQU4kxBEJHVe1IPt/5t5cuBVNG2F6lvPayxuYCqWGPE9Pj/JJrtZPBQb0IqxX9GbCwLE1rJzjXhW7LMZPobvNGDM924zWr0+YQb67WsOsVrH2ilSRIznEYtW27qiIvyJA07JqczCIqTgARrcHhA7nsNtCXqnr3G+3avcHVLCwbsjKNk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Two-Little-Women-on-a-Holiday_5893
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy